apiVersion: apps/v1
kind: Deployment
metadata:
  name: apigee-service
  labels:
    app: apigee
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apigee
  template:
    metadata:
      labels:
        app: apigee
    spec:
      containers:
      - name: apigee
        image: google/apigee-envoy-adapter:v2.1.4
        ports:
        - containerPort: 10000
        args:
        - "-c"
        - "/etc/config/config.yaml"
        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /etc/config/application_default_credentials.json
        volumeMounts:
        - name: envoy-config
          mountPath: /etc/config
      volumes:
        - name: envoy-config
          secret:
            secretName: envoy-config